ALL_CITIES = [
  "Abington",
  "Acton",
  "Acushnet",
  "Adams",
  "Agawam",
  "Allston",
  "Amesbury",
  "Amherst",
  "Andover",
  "Arlington",
  "Ashburnham",
  "Ashby",
  "Ashfield",
  "Ashland",
  "Assonet",
  "Athol",
  "Attleboro",
  "Auburn",
  "Auburndale",
  "Avon",
  "Ayer",
  "Baldwinville",
  "Barnstable",
  "Barre",
  "Becket",
  "Bedford",
  "Belchertown",
  "Bellingham",
  "Belmont",
  "Berkley",
  "Berlin",
  "Bernardston",
  "Beverly",
  "Billerica",
  "Blackstone",
  "Blandford",
  "Bolton",
  "Bondsville",
  "Boston",
  "Bourne",
  "Boxboro",
  "Boylston",
  "Bradford",
  "Braintree",
  "Brant Rock",
  "Brewster",
  "Bridgewater",
  "Brighton",
  "Brimfield",
  "Brockton",
  "Brookfield",
  "Brookline",
  "Burlington",
  "Buzzards Bay",
  "Byfield",
  "Cambridge",
  "Canton",
  "Carver",
  "Cataumet",
  "Centerville",
  "Charlemont",
  "Charlestown",
  "Charlton",
  "Charlton City",
  "Chatham",
  "Chelmsford",
  "Chelsea",
  "Cherry Valley",
  "Cheshire",
  "Chestnut Hill",
  "Chicopee",
  "Clarksburg",
  "Clinton",
  "Cohasset",
  "Colrain",
  "Concord",
  "Conway",
  "Cotuit",
  "Dalton",
  "Danvers",
  "Dartmouth",
  "Dedham",
  "Deerfield",
  "Dennis",
  "Dennisport",
  "Devens",
  "Dighton",
  "Dorchester",
  "Douglas",
  "Dover",
  "Dracut",
  "Dudley",
  "Dunstable",
  "Duxbury",
  "E Boston",
  "E Bridgewater",
  "E Brookfield",
  "E Dennis",
  "E Falmouth",
  "E Freetown",
  "E Longmeadow",
  "E Otis",
  "E Taunton",
  "E Templeton",
  "E Walpole",
  "E Wareham",
  "E Weymouth",
  "Eastham",
  "Easthampton",
  "Easton",
  "Edgartown",
  "Egremont",
  "Erving",
  "Essex",
  "Everett",
  "Fairhaven",
  "Fall River",
  "Falmouth",
  "Feeding Hills",
  "Fiskdale",
  "Fitchburg",
  "Florence",
  "Forestdale",
  "Foxboro",
  "Framingham",
  "Franklin",
  "Freetown",
  "Gardner",
  "Georgetown",
  "Gilbertville",
  "Gill",
  "Gloucester",
  "Goshen",
  "Grafton",
  "Granby",
  "Granville",
  "Great Barrington",
  "Greenfield",
  "Groton",
  "Groveland",
  "Gt Barrington",
  "Hadley",
  "Halifax",
  "Hamilton",
  "Hampden",
  "Hanover",
  "Hanson",
  "Hardwick",
  "Harwich",
  "Harwich Port",
  "Hatfield",
  "Haverhill",
  "Haydenville",
  "Hingham",
  "Hinsdale",
  "Holbrook",
  "Holden",
  "Holland",
  "Holliston",
  "Holyoke",
  "Hopedale",
  "Hopkinton",
  "Housatonic",
  "Hubbardston",
  "Hudson",
  "Hull",
  "Humarock",
  "Huntington",
  "Hyannis",
  "Hyde Park",
  "Indian Orchard",
  "Ipswich",
  "Jamaica Plain",
  "Kingston",
  "Lakeville",
  "Lancaster",
  "Lanesboro",
  "Lanesborough",
  "Lawrence",
  "Lee",
  "Leeds",
  "Leicester",
  "Lenox",
  "Lenoxdale",
  "Leominster",
  "Lexington",
  "Lincoln",
  "Linwood",
  "Littleton",
  "Longmeadow",
  "Lowell",
  "Ludlow",
  "Lunenburg",
  "Lynn",
  "Lynnfield",
  "Malden",
  "Manchaug",
  "Manchester",
  "Manchester By The Se",
  "Manomet",
  "Mansfield",
  "Marblehead",
  "Marion",
  "Marlboro",
  "Marlborough",
  "Marshfield",
  "Marstons Mills",
  "Mashpee",
  "Mattapan",
  "Mattapoisett",
  "Maynard",
  "Medfield",
  "Medford",
  "Medway",
  "Melrose",
  "Mendon",
  "Merrimac",
  "Methuen",
  "Middleboro",
  "Middleborough",
  "Middleton",
  "Milford",
  "Millbury",
  "Millers Falls",
  "Millis",
  "Millville",
  "Milton",
  "Monson",
  "Monument Beach",
  "N Adams",
  "N Amherst",
  "N Andover",
  "N Attleboro",
  "N Billerica",
  "N Brookfield",
  "N Chelmsford",
  "N Dartmouth",
  "N Dighton",
  "N Eastham",
  "N Easton",
  "N Falmouth",
  "N Grafton",
  "N Hatfield",
  "N Oxford",
  "N Quincy",
  "N Reading",
  "N Truro",
  "N Uxbridge",
  "N Weymouth",
  "Nahant",
  "Nantucket",
  "Natick",
  "Needham",
  "New Bedford",
  "New Salem",
  "Newbury",
  "Newburyport",
  "Newton",
  "Norfolk",
  "North Attleborough",
  "Northampton",
  "Northboro",
  "Northborough",
  "Northbridge",
  "Northfield",
  "Norton",
  "Norwell",
  "Norwood",
  "Oak Bluffs",
  "Oakham",
  "Onset",
  "Orange",
  "Orleans",
  "Osterville",
  "Oxford",
  "Palmer",
  "Paxton",
  "Peabody",
  "Pembroke",
  "Pepperell",
  "Petersham",
  "Phillipston",
  "Pittsfield",
  "Plainfield",
  "Plainville",
  "Plymouth",
  "Plympton",
  "Pocasset",
  "Princeton",
  "Provincetown",
  "Quincy",
  "Randolph",
  "Raynham",
  "Reading",
  "Readville",
  "Rehoboth",
  "Revere",
  "Rochdale",
  "Rochester",
  "Rockland",
  "Rockport",
  "Roslindale",
  "Rowley",
  "Roxbury",
  "Royalston",
  "Russell",
  "Rutland",
  "S Attleboro",
  "S Boston",
  "S Carver",
  "S Chatham",
  "S Dartmouth",
  "S Deerfield",
  "S Dennis",
  "S Easton",
  "S Grafton",
  "S Hadley",
  "S Hamilton",
  "S Lancaster",
  "S Weymouth",
  "S Yarmouth",
  "Sagamore",
  "Sagamore Beach",
  "Salem",
  "Salisbury",
  "Sandisfield",
  "Sandwich",
  "Saugus",
  "Scituate",
  "Seekonk",
  "Sharon",
  "Sheffield",
  "Shelburne",
  "Shelburne Falls",
  "Sheldonville",
  "Sherborn",
  "Shirley",
  "Shrewsbury",
  "Somerset",
  "Somerville",
  "South Hadley",
  "Southampton",
  "Southboro",
  "Southborough",
  "Southbridge",
  "Southwick",
  "Spencer",
  "Springfield",
  "Sterling",
  "Stockbridge",
  "Stoneham",
  "Stoughton",
  "Stow",
  "Sturbridge",
  "Sudbury",
  "Sunderland",
  "Sutton",
  "Swampscott",
  "Swansea",
  "Taunton",
  "Teaticket",
  "Templeton",
  "Tewksbury",
  "Thorndike",
  "Three Rivers",
  "Topsfield",
  "Townsend",
  "Turners Falls",
  "Tyngsboro",
  "Tyngsborough",
  "Upton",
  "Uxbridge",
  "Vineyard Haven",
  "W Boylston",
  "W Bridgewater",
  "W Brookfield",
  "W Chatham",
  "W Dennis",
  "W Harwich",
  "W Newbury",
  "W Newton",
  "W Peabody",
  "W Roxbury",
  "W Springfield",
  "W Stockbridge",
  "W Tisbury",
  "W Wareham",
  "W Warren",
  "W Yarmouth",
  "Wakefield",
  "Wales",
  "Walpole",
  "Waltham",
  "Ware",
  "Wareham",
  "Warren",
  "Watertown",
  "Wayland",
  "Webster",
  "Wellesley",
  "Wellfleet",
  "Wenham",
  "West Bridgewater",
  "Westboro",
  "Westborough",
  "Westfield",
  "Westford",
  "Westminster",
  "Weston",
  "Westport",
  "Westwood",
  "Weymouth",
  "Whately",
  "White Horse Bch",
  "White Horse Beach",
  "Whitinsville",
  "Whitman",
  "Wilbraham",
  "Williamsburg",
  "Williamstown",
  "Wilmington",
  "Winchendon",
  "Winchester",
  "Windsor",
  "Winthrop",
  "Woburn",
  "Woods Hole",
  "Worcester",
  "Worthington",
  "Wrentham",
  "Yarmouth",
  "Yarmouth Port"
]
